#!/bin/sh

README=./readme.md
TEMPLATE=./readme-template.md
RM_COMPONENT=./src/components/camera-component/readme.md
RM_CONTROLLER=./src/components/camera-controller/readme.md
ROADMAP=./roadmap.md

echo '<!-- AUTO GENERATED: Do not edit this file, edit readme-template.md instead -->' > "$README"
echo '' >> "$README"
cat "$TEMPLATE" >> "$README"
cat "$RM_COMPONENT" >> "$README"
echo '' >> "$README"
echo '' >> "$README"
cat "$RM_CONTROLLER" >> "$README"
echo '' >> "$README"
echo '' >> "$README"
cat "$ROADMAP" >> "$README"